### ISSUE TITLE
MODX Manager styles in subdirectory with compress_css enabled

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#11142]
Upon migrating a 2.2.12-pl instance to a new development server, the new instance was placed in a subdirectory for testing.

After rerunning setup, completely wiping ```core/cache/```, etc. I still could not get the icons in the tree to show up... it turns out, the CSS minify of ```manager/templates/default/css/index.css``` (with compress_css = true in System Settings) was the culprit.

It was converting CSS paths to absolute, dropping the subdirectory:
```css
#ux-lightbox-loading{
   background:url("/manager/templates/default/images/style/loading.gif"); /*...*/
}
```

Disabling ```compress_css``` seems to fix the issue, but it was working just fine with the instance running at the root of the domain.

This seems like a bug with compress_css and some Manager styles (via a subdirectory), unless I've missed updating something obvious? Everything else seems to be functioning as expected.
