### ISSUE TITLE
[3.0.0-rc1] Image in package manager

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#15989]
### Summary

If you go to the package manager, you can see a pale image on the main background =)

![изображение](https://user-images.githubusercontent.com/3787132/150679178-75e5a1be-cf2a-43e1-86ca-21ce1ed6eed0.png)

Tinted the background color to make it easier to see:

![изображение](https://user-images.githubusercontent.com/3787132/150679462-fc0cf2fd-8234-4b4f-8e20-ecfaedd735c1.png)

This style that shows the picture is in the following location:

`index.css:26338`

```css
#modx-panel-packages.drag-n-drop::before {
    background: transparent url("../images/restyle/dragndrop.svg");
    ...
}
```

### Environment

- MODX 3.0.0-rc1
- Firefox 96.0.1
